version: "3"

services:
  nacos:
    build:
      context: .
      dockerfile: ./Dockerfile-nacos
    container_name: nacos
    restart: always
    entrypoint: /app/wait-for-it.sh mysql:3306 -- bin/docker-startup.sh
    depends_on:
      - mysql
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_demo_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=Japan
    networks:
      - web-demo
  web:
    build:
      context: .
      dockerfile: ./spring-cloud-web-demo
    container_name: web-demo
    entrypoint: ./wait-for-it.sh nacos:8848 --
    ports:
      - "8001:8001"
    depends_on:
      - nacos
      - mysql
    networks:
      - web-demo
    restart: always
  gateway:
    build:
      context: .
      dockerfile: ./spring-cloud-gateway-demo
    container_name: gateway-demo
    entrypoint: ./wait-for-it.sh nacos:8848 --
    ports:
      - "80:80"
    depends_on:
      - nacos
      - mysql
    networks:
      - web-demo
    restart: always
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - web-demo
networks:
  web-demo:
