version: "3"

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - web-demo

networks:
  web-demo:
