server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/de/**

